fProject/fProject/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fProject/main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns = [
    path('items', views.product_list, name='product_list'),
    path('items/<slug:category_slug>/', views.product_list, name="product_list_by_category"),
    path('items/<str:nameFilter>/', views.product_list, name="product_filtered"),
    path('items/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('items/create', views.create, name='add_product'),
    path('items/update/<int:pk>', views.update, name='update_product'),
    path(r'^items/del/(?P<pk>\d+)/$', views.delete, name='delete_product')
]

fProject/main/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    storage1 = models.PositiveIntegerField(default=0)
    storage2 = models.PositiveIntegerField(default=0)
    unallocated = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_detail',
                       args=[self.id, self.slug])

fProject/main/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['image', 'name', 'category', 'description', 'price', 'stock', 'available', 'slug', 'storage1',
                  'storage2', 'unallocated']
        widgets = {
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.TextInput(attrs={'class': 'form-control'}),
            'stock': forms.TextInput(attrs={'class': 'form-control'}),
            'available': forms.Select(attrs={'class': 'form-control'}, choices=((True, 'Yes'), (False, 'No'))),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'storage1': forms.TextInput(attrs={'class': 'form-control', 'type': 'range'}),
            'storage2': forms.TextInput(attrs={'class': 'form-control', 'type': 'range'})
        }

fProject/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product
from .forms import ProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    nameFilter = request.GET.get("nameFilter")
    if nameFilter:
        products = products.filter(name__contains=nameFilter)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'shop/product/detail.html',
                  {'product': product})


def create(request):
    form = ProductForm()

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
    if(form.is_valid()):
        form.save()
        return render(request, 'shop/product/list.html')

    context = {
        'form': form
    }
    return render(request, 'shop/product/add.html', context)


def update(request, pk):
    product = Product.objects.get(id=pk)

    form = ProductForm(instance=product)

    if request.method == 'POST':
        post = request.POST.copy()
        slider1_val = int(request.POST.get('storage1'))
        slider2_val = int(request.POST.get('storage2'))
        post['unallocated'] = int(post['stock']) - slider1_val - slider2_val
        request.POST = post
        form = ProductForm(request.POST, request.FILES, instance=product)
        if(form.is_valid()):
            form.save()
            return render(request, 'shop/product/list.html')

    context = {
        'form': form
    }

    return render(request, 'shop/product/update.html', context)


def delete(request, pk):
    object = Product.objects.filter(pk=pk)
    object.delete()
    return render(request, 'shop/product/list.html')

fProject/main/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            {% block title %}Мой магазин{% endblock %}
        </title>
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    </head>
    <body>
        <div id="header">
        <a href="/items" class="logo">Мой магазин</a>
        </div>
        <div id="subheader">
        <div class="cart">Корзина пустая.</div>
        </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>

    </body>
</html>

fProject/main/templates/shop/product/add.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            {% block title %}Добавление товара{% endblock %}
        </title>
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    </head>
    <body>
        <div id="header">
        <a href="/items" class="logo">Мой магазин</a>
        </div>
    <h1>Создайте товар на этой страничке</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
    </body>
</html>

fProject/main/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
<img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static 'img/no_image.png' %}{% endif %}">
<h1>{{ product.name }}</h1>
<h2>
<a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
</h2>
<p class="price">${{ product.price }}</p>
{{ product.description|linebreaks }}
</div>
{% endblock %}

fProject/main/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
<h3>Категория</h3>
<ul>
<li {% if not category %}class="selected"{% endif %}>
<a href="{% url 'main:product_list' %}">Все</a>
</li>
{% for c in categories %}
<li {% if category.slug == c.slug %}class="selected" {% endif %}>
<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
</li>
{% endfor %}
</ul>
</div>
<div id="main" class="product-list">
<h1>{% if category %}{{ category.name }}{% else %}Товар{% endif %}</h1>
{% for product in products %}
<div class="item">
<a href="{{ product.get_absolute_url }}">
    <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}">
</a>
<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
<br>
${{ product.price }}
        <a class="btn btn-primary" href="{% url 'main:delete_product' pk=product.pk %}">Удалить</a>
    <a href="{% url 'main:update_product' pk=product.pk %}" class="btn btn-primary">Обновить товар</a>
</div>
{% endfor %}
</div>
<div><a href="{% url 'main:add_product' %}" class="btn btn-primary">Добавить товар</a></div>


<form action="/items" method="get">
        <label for="results">Введите фильтр: </label>
        <input id="results" type="text" name="nameFilter">
        <input type="submit" value="Поиск">
    </form>
{% endblock %}

fProject/main/templates/shop/product/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Обновление продукта</title>
            <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>
<body>
        <div id="header">
        <a href="/items" class="logo">Мой магазин</a>
        </div>
    <h1>Обновите товар на этой страничке</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
    </body>
</html>